---
- name: download ovs binaries
  get_url:
    validate_certs: "{{ validate_certs }}"
    dest: "{{ item.dest }}"
    url: "{{ item.url }}"
  with_items:
    - {
        url: "{{ deb_ovs_common_url }}",
        dest: /tmp/ovs-common.deb
      }
    - {
        url: "{{ deb_ovs_switch_url }}",
        dest: /tmp/ovs-switch.deb
      }

- name: install ovs-common
  apt: "deb=/tmp/ovs-common.deb"

- name: install ovs
  apt: "deb=/tmp/ovs-switch.deb"
