---
- name: download ovs binaries
  get_url:
    validate_certs: "{{ validate_certs }}"
    dest: "{{ item.dest }}"
    url: "{{ item.url }}"
  with_items:
    - {
        url: "https://cisco.box.com/shared/static/zzmpe1zesdpf270k9pml40rlm4o8fs56.rpm",
        dest: /tmp/openvswitch-2.3.1-2.el7.x86_64.rpm
      }

- name: install ovs
  yum: name=/tmp/openvswitch-2.3.1-2.el7.x86_64.rpm state=present

- name: start ovs service
  service: "name=openvswitch enabled=yes state=started"

- name: setup ovs
  shell: "ovs-vsctl set-manager {{ item }}"
  with_items:
    - "tcp:127.0.0.1:6640"
    - "ptcp:6640"

- name: check selinux status
  shell: sestatus
  register: selinux_set

- name: permit openvswitch_t type in selinux
  shell: semanage permissive -a openvswitch_t
  when: selinux_set.stdout | search(".*SELinux status:.*enabled.*")
  become: true
